theme: minima
markdown: kramdown
baseurl: "/meu-blog"
title: "Meu Blog"
author: "Tiago Moreira"
email: tiagomoreira@ttmora.onmicrosoft.com
description: "Blog pessoal sobre tecnologia e automação"
exclude:
  - Servidor Jekyll
  - go
  - automacao
  - README.md
  - .gitignore
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
